project_id = "uipdlykacbzuunznexgd"

[functions.create-profile]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-due-notification]
verify_jwt = true